### ISSUE TITLE
ER Diagram Draw

### ISSUE THREAD

**Issue by sahaavi** [bachelorsfield/bachelorsfield.github.io#2]
Draw ER Diagrams using DIA

**Comment by pronay19** [comment]
**Diagrams**

- Activity Diagram

![activity](https://user-images.githubusercontent.com/60335986/76494864-f4cd7e00-645f-11ea-8e60-01e2a78d32c7.jpg)

- Class Diagram

![class](https://user-images.githubusercontent.com/60335986/76494990-2fcfb180-6460-11ea-970d-6149c52943ea.jpeg)

- Entity Diagram

![entity](https://user-images.githubusercontent.com/60335986/76495071-5857ab80-6460-11ea-8795-c0240acfb263.jpeg)

- Sequence Diagram

![sequence](https://user-images.githubusercontent.com/60335986/76495169-7e7d4b80-6460-11ea-9a5b-67d9fdb91bbd.jpeg)

- Usecase Diagram

![usecase](https://user-images.githubusercontent.com/60335986/76495311-c8663180-6460-11ea-95bb-7b39f0b4a228.jpg)
